name: RTD build status
description: Get ReadTheDocs build status
inputs:
  rtd-project:
    type: string
    required: true
    description: The ReadTheDocs project slug.
  commit:
    type: string
    required: true
    description: |
      The commit SHA that triggered the build.
  num-latest-builds:
    type: number
    default: 10
    required: false
    description: |
      The number of latest builds to retrieve. Defaults to 10.
outputs:
  build-url:
    description: |
      The URL of the rtd-project build associated with the commit.
    value: ${{ steps.check-rtd-build.outputs.build-url }}
  url:
    description: |
      The URL of the hosted version associated with the commit.
    value: ${{ steps.check-rtd-build.outputs.url }}
runs:
  using: composite
  steps:
    - name: Check RTD build status
      id: check-rtd-build
      shell: bash -eo pipefail {0}
      env:
        RTD_API_URL: https://readthedocs.org/api/v3
      run: |
        endpoint=${{env.RTD_API_URL}}/projects/${{ inputs.rtd-project }}/builds/?limit=${{ inputs.num-latest-builds }}
        echo "Checking build status by running:"
        echo "curl -s $endpoint | jq '.results[] | select(.commit == \"${{ inputs.commit }}\")'"
        # Function to get the latest build for the specific version
        check_latest_build() {
          curl -s $endpoint | jq '.results[] | select(.commit == "${{ inputs.commit }}")'
        }
        # Check that builds exist
        if [ $(curl -s $endpoint | jq '.count') -eq 0 ]; then
          echo "::error::No builds found for project '${{ inputs.rtd-project }}'."
          exit 1
        fi
        # Loop until the build finishes (success or failure)
        while true; do
          latest_build_res=$(check_latest_build)
          status=$(jq -r '.success' <<< $latest_build_res)
          if [ "$status" == "null" ]; then
            echo "Build still in progress..."
            sleep 20 # Wait and retry
          elif [ "$status" == "true" ]; then
            echo "Build succeeded."
            build_url=$(jq -r '.urls.build' <<< $latest_build_res)
            version_endpoint=$(jq -r '._links.version' <<< $latest_build_res)
            # Get documentation url
            url=$(curl -s $version_endpoint | jq -r '.urls.documentation')
            if [[ $url == null ]]; then # Pull request
              pr_num=$(jq -r '.version' <<< $latest_build_res)
              url=https://${{inputs.rtd-project}}--${pr_num}.org.readthedocs.build/
            fi
            echo "build-url=$build_url" >> $GITHUB_OUTPUT
            echo "url=$url" >> $GITHUB_OUTPUT
            break
          elif [ -z "$status" ]; then
            echo "::error::Build for project '${{ inputs.rtd-project }}' associated to commit ${{ inputs.commit }} not found within the latest ${{inputs.num-latest-builds}} builds."
            exit 1
          elif [ "$status" == "false" ]; then
              echo "::error::There was an error in the ReadTheDocs build. For further information, check the build logs: $build_url"
              exit 1
          else
              echo "ERROR: Unexpected build status: $status"
              exit 1
          fi
        done